# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cafeteria_pb2 as cafeteria__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cafeteria_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CafeteriaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeWeekday = channel.unary_stream(
                '/cafeteria.CafeteriaService/SubscribeWeekday',
                request_serializer=cafeteria__pb2.WeekdaySubscriptionRequest.SerializeToString,
                response_deserializer=cafeteria__pb2.Menu.FromString,
                _registered_method=True)
        self.SubscribeCuisine = channel.unary_stream(
                '/cafeteria.CafeteriaService/SubscribeCuisine',
                request_serializer=cafeteria__pb2.CuisineSubscriptionRequest.SerializeToString,
                response_deserializer=cafeteria__pb2.Menu.FromString,
                _registered_method=True)


class CafeteriaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeWeekday(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCuisine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CafeteriaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeWeekday': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeWeekday,
                    request_deserializer=cafeteria__pb2.WeekdaySubscriptionRequest.FromString,
                    response_serializer=cafeteria__pb2.Menu.SerializeToString,
            ),
            'SubscribeCuisine': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCuisine,
                    request_deserializer=cafeteria__pb2.CuisineSubscriptionRequest.FromString,
                    response_serializer=cafeteria__pb2.Menu.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafeteria.CafeteriaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CafeteriaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeWeekday(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cafeteria.CafeteriaService/SubscribeWeekday',
            cafeteria__pb2.WeekdaySubscriptionRequest.SerializeToString,
            cafeteria__pb2.Menu.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCuisine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cafeteria.CafeteriaService/SubscribeCuisine',
            cafeteria__pb2.CuisineSubscriptionRequest.SerializeToString,
            cafeteria__pb2.Menu.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
