# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cafeteria.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61\x66\x65teria.proto\x12\tcafeteria\"\x95\x01\n\x04Menu\x12\n\n\x02id\x18\x01 \x01(\x05\x12#\n\x07\x63uisine\x18\x02 \x01(\x0e\x32\x12.cafeteria.Cuisine\x12\x1f\n\x03\x64\x61y\x18\x03 \x01(\x0e\x32\x12.cafeteria.Weekday\x12\x11\n\tdish_name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x13\n\x0bingredients\x18\x06 \x03(\t\"A\n\x1a\x43uisineSubscriptionRequest\x12#\n\x07\x63uisine\x18\x02 \x01(\x0e\x32\x12.cafeteria.Cuisine\"A\n\x1aWeekdaySubscriptionRequest\x12#\n\x07weekday\x18\x02 \x01(\x0e\x32\x12.cafeteria.Weekday*K\n\x07Weekday\x12\x13\n\x0fUNKNOWN_WEEKDAY\x10\x00\x12\x07\n\x03MON\x10\x01\x12\x07\n\x03TUE\x10\x02\x12\x07\n\x03WED\x10\x03\x12\x07\n\x03THU\x10\x04\x12\x07\n\x03\x46RI\x10\x05*P\n\x07\x43uisine\x12\x13\n\x0fUNKNOWN_CUISINE\x10\x00\x12\n\n\x06POLISH\x10\x01\x12\x0b\n\x07ITALIAN\x10\x02\x12\n\n\x06INDIAN\x10\x03\x12\x0b\n\x07MEXICAN\x10\x04\x32\xb2\x01\n\x10\x43\x61\x66\x65teriaService\x12N\n\x10SubscribeWeekday\x12%.cafeteria.WeekdaySubscriptionRequest\x1a\x0f.cafeteria.Menu\"\x00\x30\x01\x12N\n\x10SubscribeCuisine\x12%.cafeteria.CuisineSubscriptionRequest\x1a\x0f.cafeteria.Menu\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cafeteria_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEEKDAY']._serialized_start=316
  _globals['_WEEKDAY']._serialized_end=391
  _globals['_CUISINE']._serialized_start=393
  _globals['_CUISINE']._serialized_end=473
  _globals['_MENU']._serialized_start=31
  _globals['_MENU']._serialized_end=180
  _globals['_CUISINESUBSCRIPTIONREQUEST']._serialized_start=182
  _globals['_CUISINESUBSCRIPTIONREQUEST']._serialized_end=247
  _globals['_WEEKDAYSUBSCRIPTIONREQUEST']._serialized_start=249
  _globals['_WEEKDAYSUBSCRIPTIONREQUEST']._serialized_end=314
  _globals['_CAFETERIASERVICE']._serialized_start=476
  _globals['_CAFETERIASERVICE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
